name: Tranksfer Files from PikPak to OneDrive

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'The path to copy'
        required: true
        default: 'example/path'

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone
        # Write Rclone configuration file
        echo '[p]' > ~/.config/rclone/rclone.conf
        echo 'type = pikpak' >> ~/.config/rclone/rclone.conf
        echo 'user = udiskboot@gmail.com' >> ~/.config/rclone/rclone.conf
        echo 'pass = 1nhhx-0rSNold8UegWVDKnJCkWNaQKEh' >> ~/.config/rclone/rclone.conf
        echo 'token = {"access_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6ImYyMGQ5NGU5LWNjNDYtNGFkZi04MjM1LWQ4YjI1ZjQyOGRiYiJ9.eyJpc3MiOiJodHRwczovL3VzZXIubXlwaWtwYWsuY29tIiwic3ViIjoiWXhWOExQNzVZQnFVMnpGUiIsImF1ZCI6IllOeFQ5dzdHTWRXdkVPS2EiLCJleHAiOjE3MjE1NTMxOTUsImlhdCI6MTcyMTU0NTk5NSwiYXRfaGFzaCI6InIuc3Rsa2tFY3dFZS1yMEFxNXFzNzlHUSIsInNjb3BlIjoidXNlciBwYW4gc3luYyBvZmZsaW5lIiwicHJvamVjdF9pZCI6IjJ3a3M1NmMzMWRjODBzeG01cDkiLCJtZXRhIjp7ImEiOiJmRlBoUGdFNWlqMTE3OTdlMEhPQ3QvbXpUTVFXZHNYWjBYWHFSZEJRUWNFPSJ9fQ.elP61zgPz4m9Lq5JC6kCSMjXjIqkxhnAWZ5KpSD0mEk3fEMxLI_JVMUG8_wlfTfzUQuJU426jsOWsPLzWkVnzkAiZ_qnLrnfy9HKxsHH5Kj2PaYKBnyX1M-X-FsmpRO2NR29RmZiIXLxdbc3mtOe9dF89Fk8K9Cd4kulhbTS7QGsq7rMzftdqsrWoSYMK-CPbbJ0dxYZ5vO7rAJjC4PeLFRvG5_5vNtlr3B_wkyG_qtw9X-epx4jFLskhLLtByADy1J_JJGx_ZC8oFUXsW6whdM-Fs52X_QIN36Yi_nAEGgXD2btUTm4t3B3MgMdk8KytKmC_iHCDf6Xlj3YpLRuHg","token_type":"Bearer","refresh_token":"os.S0jgnclQKmactQsZ7-suLfPQb4SusyK-WMud0JWaMlhn0jirgFRQZ_hLQrI2","expiry":"2024-07-21T17:13:14.921130723+08:00"}' >> ~/.config/rclone/rclone.conf
        echo '' >> ~/.config/rclone/rclone.conf
        echo '[o]' >> ~/.config/rclone/rclone.conf
        echo 'type = onedrive' >> ~/.config/rclone/rclone.conf
        echo 'token = {"access_token":"eyJ0eXAiOiJKV1QiLCJub25jZSI6IjZqdkEtZXM5Ym84ajltNW9Yc0ZaM3JXNFhIQWpoMU9nODhPN0tKWXB1eUEiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyIsImtpZCI6Ik1HTHFqOThWTkxvWGFGZnBKQ0JwZ0I0SmFLcyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85ODMwMWM3ZS0yMjhhLTQyZWUtOGJjMi0yOWZkZjU0NzY0MjAvIiwiaWF0IjoxNzIxNTQ1Mzc3LCJuYmYiOjE3MjE1NDUzNzcsImV4cCI6MTcyMTU1MDM4MywiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhYQUFBQU5pRTM2WTBPV1RHU3F1K3pjOGVFN2pSYng0ZDVtZ3RISzFDUjlBaDZncWNEbDlicGxKaUlqbWpibGZIUnlaRzAiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6InJjbG9uZSIsImFwcGlkIjoiYjE1NjY1ZDktZWRhNi00MDkyLTg1MzktMGVlYzM3NmFmZDU5IiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJMZW8iLCJnaXZlbl9uYW1lIjoiSmFjayIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjExMS4yNDYuNDEuMTkzIiwibmFtZSI6IkphY2sgTGVvIiwib2lkIjoiMjUzNGFjZTEtYmMyZi00MDc3LWEwZmQtYTM3ZmUwMDNlYjhhIiwicGxhdGYiOiIxNCIsInB1aWQiOiIxMDAzMjAwMjkwQkNEOENEIiwicmgiOiIwLkFWWUFmaHd3bUlvaTdrS0x3aW45OVVka0lBTUFBQUFBQUFBQXdBQUFBQUFBQUFDZkFDSS4iLCJzY3AiOiJGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWRXcml0ZSBGaWxlcy5SZWFkV3JpdGUuQWxsIFNpdGVzLlJlYWQuQWxsIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic3ViIjoiVEdWeWdjTUw1RjcyWmplcXRBZi1iQXhnNjM4eG0teHNtb0FTY1lRTHlkMCIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6Ijk4MzAxYzdlLTIyOGEtNDJlZS04YmMyLTI5ZmRmNTQ3NjQyMCIsInVuaXF1ZV9uYW1lIjoidWRpc2tib290QDVwMTRsMi5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJ1ZGlza2Jvb3RANXAxNGwyLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6Ink3UVZCaG13bkVHYlNWQ25kUjV1QUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjYyZTkwMzk0LTY5ZjUtNDIzNy05MTkwLTAxMjE3NzE0NWUxMCIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfaWRyZWwiOiIxIDYiLCJ4bXNfc3QiOnsic3ViIjoiMmRYVXBVdGFSWlU2TVZDelY0Qk1zXzZLY2Z5czVNUlByS196RXpMSmFMdyJ9LCJ4bXNfdGNkdCI6MTY4MDU3MDUwNn0.vveXZ7V5nuvYOKP_Fe73i0-Ftj_qjqvRwEsGuFDUVttUw7MVV8JKW3TI7BhZWzqLaqfyQy-5XmvGbbicnuwwGF5YhH0nhTYe3j3vPG6tGOgj5709hsXzH_2e9Tcxx1AC6Oq7g0u2qeGffXF8mAbRW_WvG2GAmcZwrm6NjYSxR38LNr9qNW5L7re_Ptn9zb2KruVt0NIEU6PP7Wj_rUU7IELBb3NBuPjHazzuEbVg0VjfxzvpkUNFR3yVYHr9YfmYiuXTAZTUkVeQiwa7GCAf2fmQDWtrzY6it5rip9Cu82HBT2m2IY1Zn2-PUmrii4-G2VJlaXgsGzsEGs1XIHPOEg","token_type":"Bearer","refresh_token":"0.AVYAfhwwmIoi7kKLwin99UdkINllVrGm7ZJAhTkO7Ddq_VmfACI.AgABAwEAAAApTwJmzXqdR4BN2miheQMYAgDs_wUA9P8xRLJ0hCtvFPXnhZ1G9YyJCgfz8XK09Jo2rSM-Kyc6dhqDlF_21RJNByVbLgyBItzxxmGzITwRSU0w1axkvCTqhHYB5k9Pxn_oK8xnPLKH_Cu8r6yHUVQF3P0n5ulGS4clzuNKxOXQclVMMpslT7ReRQbdOS6WnFrKUI0UIXFnWPfcVO-e9B3SVvgUpxNWQshPRF4tkIooWIj5AuvphcTLzgODcUYFxRGF-ruVB4yBYbl481DW4Fk419yFey6SS4YOxmA07mU-AC7SaqxVhnDgI4MG1J66MXLShpeBRJUIMNXjv1aLTQwg8HQ-9lw_2Yi5eQWQJeA7XAob_arlXXgnB_mQlwK_iQgLl9dpNLXPzj_WTmc75HiDym3RiYmGkDw1oOAx_U1Zuvjv5GYQKeqX_m0u8BtjXuQD8Ikop1-904_UwwjoGUHZYjslEUefEG18Ag_4Vl2jN-9H9c2lR3Naq4707FOERMeArPtQt5ntlXtMyS2T5XJTboFZMmrnxEBpHZY1Z4rlNjjmO64HXMak9DE404jXpbCjbHxA6qiuDTkaRuBvIRPR88S7TK4byfhlmF9j04YNczgcN8FiIGRLcoV_gAq93hxC3lrb1GMBJoNX2F2AtodweDTfCOOc2HqFeFbGglrTnKfRp35lBv37N7sbhHOGBUF7AVMRqGrdIg8MCyujkjd5D4hqPBiSaXnPOsYgMeVCLlB-iA6NTg38wF4L1OV0h-lG","expiry":"2024-07-21T16:26:23.12136449+08:00"}' >> ~/.config/rclone/rclone.conf
        echo 'drive_id = b!Sn_PzsqoSU-4QS8_NFd2cHZgUvgytOVLudTjfOhiTlhcVtPn-ACTQYfUFs-TO627' >> ~/.config/rclone/rclone.conf
        echo 'drive_type = business' >> ~/.config/rclone/rclone.conf

    - name: Verify Rclone Configuration
      run: |
        rclone listremotes
        rclone config show

    - name: Check Rclone Version
      run: rclone version

    - name: Transfer files from PikPak to OneDrive
      run: |
         rclone copy p:${{ github.event.inputs.path }} o:${{ github.event.inputs.path }} --verbose --log-file=rclone.log || true
        cat rclone.log

  
