name: Transfer Files from PikPak to OneDrive

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'The path to copy'
        required: true
        default: 'example/path'

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash
        mkdir -p ~/.config/rclone
        # Create Rclone configuration file with a heredoc
        cat <<EOF > ~/.config/rclone/rclone.conf
[p]
type = pikpak
user = udiskboot@gmail.com
pass = 1nhhx-0rSNold8UegWVDKnJCkWNaQKEh
token = {"access_token":"<pikpak_access_token>","refresh_token":"<pikpak_refresh_token>","expiry":"<pikpak_expiry_date>"}

[o]
type = onedrive
token = {"access_token":"<onedrive_access_token>","refresh_token":"<onedrive_refresh_token>","expiry":"<onedrive_expiry_date>"}
EOF

    - name: Verify Rclone Configuration
      run: |
        rclone listremotes
        rclone config show

    - name: Check Rclone Version
      run: rclone version

    - name: Transfer files from PikPak to OneDrive
      run: |
        rclone copy p:/My o:/My --verbose --log-file=rclone.log || true
        cat rclone.log

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v1.2.3
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
